### ISSUE TITLE
Segues don't work after wrapping main VC with Google Cast VC

### ISSUE THREAD

**Issue by guilhermearaujo** [jonkykong/SideMenu#307] opened 2018-01-04 16:52 UTC
## New Issue Checklist

I have read the [guidelines for contributing](https://github.com/jonkykong/SideMenu/blob/master/.github/CONTRIBUTING.md) and I understand:
- [X] My issue is happening in the **latest version** of SideMenu.
- [X] My issue was **not** solved in the [README](https://github.com/jonkykong/SideMenu/blob/master/README.md).
- [ ] My issue can **not** be answered on [stackoverflow.com](stackoverflow.com).
- [x] My issue is **not** a request for new functionality that I am unwilling to build and contribute with a pull request.
- [ ] My issue **is** reproducible in the [demo project](https://github.com/jonkykong/SideMenu/tree/master/Example).

## Issue Description

My app has the following structure of view controllers:

*Main.storyboard:*
```
- TabBarController (app root; storyboard's initial VC)
  ∟ NavigationController (Tab 1)
    ∟ MainViewController
      ∟ UIButton with segue to SideMenu
  ∟ NavigationController (Tab 2)
  ∟ NavigationController (Tab 3)
  ∟ NavigationController (Tab 4)
```
*Drawer.storyboard:* 
```
- UISideMenuNavigationController (storyboard's initial VC)
  ∟ DrawerViewController
    ∟ TableView (menu options)
    ∟ Segue to (whatever)ViewController¹
```

The segue marked with **¹** will push on top of the `MainViewController`.
This configuration works very well.

I've been integrating this app with [Google Cast SDK](https://developers.google.com/cast/docs/ios_sender_setup), and part of this integration involves "wrapping" the whole VC structure with a `GCKUICastContainerViewController`. This VC will allow the app to display the mini controls used to play/pause/skip/etc you Chromecast.
Since this change, now whenever I tap one item in my menu's table view, the segue does not work, and SideMenu logs:
> SideMenu Warning: attempt to push a View Controller from Optional(<GCKUICastContainerViewController: 0x131f860d0>) where its navigationController == nil. It must be embedded in a Navigation Controller for this to work.

Obviously, this new Container is not a subclass of `UINavigationController` and therefore the segue will not work. Is there any way I can tell `UISideMenuNavigationController` how to correctly find the navigation controller it needs?

**Comment by guilhermearaujo** [comment] 2018-01-04 18:57
I started working on a [possible solution](https://github.com/guilhermearaujo/SideMenu/commits/custom-navigation-controller), but I don't think it's elegant enough for a PR.

**Comment by jonkykong** [comment] 2018-01-04 19:42
Hi @guilhermearaujo,

This is the first report of a problem of this kind. Since it is uncommon, I'm unlikely to produce a fix for it.

I can give you guidance if you would like to contribute a fix to this repository. The problem is most likely in `UISideMenuNavigationController.swift` around line **258**. Given the view hierarchy of your project, SideMenu is not finding the Navigation Controller it needs to push with. Whatever fix you produce should not break existing functionality.

In the event that you are unable to produce a fix, you can always work around this issue with a purely programmatic approach. Possible solutions:

1. Subclass GCKUICastContainerViewController and redirect all pushes sent to it to the correct navigation controller.
2. Subclass DrawerViewController and programmatically call pushes for the correct navigation controller.
3. Subclass DrawerViewController and add a delegate property so that the correct navigation controller can listen for tap events and display the appropriate screens programmatically.

I am closing this issue for now. Feel free to continue to comment for additional feedback.

**Closed by jonkykong** 2018-01-04 19:42 UTC

**Comment by guilhermearaujo** [comment] 2018-01-04 19:57
Hi @jonkykong,

Did you get the chance to check my fork? I included a delegate method that allows me to provide a custom `UINavigationController` to which other VCs would be pushed. Do you think this is a good approach, worthy of a pull request?

**Comment by jonkykong** [comment] 2018-01-04 20:06
@guilhermearaujo as you said yourself, I think that's a work-around solution that I would rather not include in the project as a one-off. The navigation controller should be discovered seamlessly without developer intervention. It seems like understanding the way the navigation controller should be discovered in your setup is the better way to go than manually specifying it.
