### ISSUE TITLE
SideMenu disables the ability to pop a view controller via a swipe gesture

### ISSUE THREAD

**Issue by wolfej94** [jonkykong/SideMenu#596] opened 2020-01-28 14:13 UTC
- [X] My issue is happening in the **latest version** of SideMenu (older versions are no longer maintained).
- [X] My issue was **not** solved in the [README](https://github.com/jonkykong/SideMenu/blob/master/README.md).
- [X] My issue can **not** be answered on [stackoverflow.com](stackoverflow.com).
- [X] My issue is **not** a request for new functionality that I am unwilling to build and contribute with a pull request.
- [X] My issue **is** reproducible in the [demo project](https://github.com/jonkykong/SideMenu/tree/master/Example).

In my project I have a side menu navigation controller being pushed by my root view which has an embedded navigation controller in it. 
Side menu seems to be disabling my ability to swipe the edge of the screen to pop the view controller, even though I have disabled the `enableSwipeToDismiss` variable on the SwipeMenu itself.

Steps to reproduce the behaviour:
1. Add a View to a storyboard
2. Embed a navigation controller in the view
3. Show a SideMenuNavigationController via a button press
4. Disable the `enableSwipeToDismiss` variable on the SideMenuNavigationController
5. Push any number of viewControllers onto the embedded navigation controllers stack
6. Attempt a swipe from the edge to pop the view controllers from the stack
7. See issue

I would expect `enableSwipeToDismiss` not to interfere with any swipe gestures from the edge of the screen when the value is false.

**Comment by caobug** [comment] 2020-02-01 14:48
I have the same problem.

**Comment by mejiagarcia** [comment] 2020-02-15 17:41
I ran into the same problem and just found a temporal fix for this, put this on your presentation view controller:

```swift
   override func viewDidAppear(_ animated: Bool) {
        super.viewDidAppear(animated)
        
        navigationController?.interactivePopGestureRecognizer?.delegate = self
        navigationController?.interactivePopGestureRecognizer?.isEnabled = true
    }
```

**Comment by jonkykong** [comment] 2020-03-27 19:25
Please reproduce this in the demo project because it is working as expected, then reopen this issue.

**Closed by jonkykong** 2020-03-27 19:25 UTC
Labels: Bug - Help Wanted!
