### ISSUE TITLE
Crash if touch during swipe

### ISSUE THREAD

**Issue by nahouto** [jonkykong/SideMenu#45] opened 2016-07-11 13:41 UTC
Hello,

I fell into a crash/bug in the example demo.
When you swipe on the left edge, if you are in middle of swiping (= do not release your finger) then clicking (once or repeatedly) on a cell in the table ("Push View Controller 1"), the app simply freezes after releasing any touch.

More clearly :
1. Swipe left with your right finger and do not release it
2. Touch "Push View Controller 1" cell with your left finger
3. Release your right finger 

The app is frozen !

Can you investigate this problem ?

Thank you !

**Comment by jonkykong** [comment] 2016-07-11 17:03
Hi @nahouto,

Thanks for finding this, it's certainly an interesting, albeit unlikely corner case. I found that if I tap multiple times I could get it to freeze, however single taps seemed to be just fine.

I'm not completely clear on the underlying root cause for this behavior, but I think the solution here will be to disable user interaction on the menus until they are fully exposed. I'll see about getting a fix for it soon.

Jon

**Comment by nahouto** [comment] 2016-07-12 06:40
Thank you, I tried to disable user interaction on the menus before viewDidAppear but without success

**Comment by jonkykong** [comment] 2016-07-14 23:14
@nahouto this has been fixed in 1.1.8. Please run `pod update` in your project to grab the latest.

**Closed by jonkykong** 2016-07-14 23:14 UTC
