### ISSUE TITLE
Mutli Touch on SlideIn/Dissolve menus

### ISSUE THREAD

**Issue by Rashidium** [jonkykong/SideMenu#127] opened 2017-01-09 09:01 UTC
SlideIn and Dissolve menus crash with multi touch gestures. Tried with the latest 2.1.3 version's Example project.

'NSInvalidArgumentException', reason: 'Application tried to present modally an active controller <Example.SideMenuTableView: 0x100b1f5a0>.'

**Comment by jonkykong** [comment] 2017-01-09 09:17
Closing for failure to follow issue template.

**Closed by jonkykong** 2017-01-09 09:17 UTC

**Comment by Rashidium** [comment] 2017-01-09 10:08
Do you mean [Contribution Guidelines](https://github.com/jonkykong/SideMenu/blob/master/.github/CONTRIBUTING.md) by "issue template"?

**Comment by jonkykong** [comment] 2017-01-09 10:11
When opening an issue on github.com, the issue is prepopulated with a [template](https://github.com/jonkykong/SideMenu/blob/master/.github/ISSUE_TEMPLATE.md). This has helped me avoid generic questions from new developers looking for help.

**Comment by Rashidium** [comment] 2017-01-09 11:10
But the issue is always reproducible with SideMenu types SlideIn or Dissolve. Just need to make multi touch gesture (1st gesture to open menu, 2nd to change its with by swiping). If 1st gesture is release first, application crashes.

**Comment by jonkykong** [comment] 2017-01-09 20:49
@Rashidium I strongly recommend that you follow the guidelines that any developer asks for in their repositories. Following their process streamlines their turn-around by giving them the information they need at the outset, minimizing follow-up conversations and gets you results faster which makes you happy. The processes exist for a reason and it's not asking for much in return for free code.

I've fixed this in 2.1.4.

**Comment by Rashidium** [comment] 2017-01-10 07:31
@jonkykong Thanks for your recommendation and fix!
