### ISSUE TITLE
Not working on iOS / iPadOS 14.2 Beta (2)

### ISSUE THREAD

**Issue by vitwo** [jonkykong/SideMenu#653] opened 2020-10-04 15:02 UTC
Maybe a beta (2) problem, maybe not...

**Comment by OIO-WPK** [comment] 2020-10-05 05:54
symptoms:
- opening the SideMenu the first time is fine; dismissal is also normal
- trying to open the SideMenu subsequently does not work; CPU usage goes up to 100%

Likely an iOS 14.2 beta 2 issue; beta 2 has been buggy as hell...
- no problem on 14.0, 14.0.1, or 14.2 beta 1

**Comment by cbalsalobre** [comment] 2020-10-05 10:55
Same here! Hopefully it is solved on beta 3

**Comment by saudeon** [comment] 2020-10-05 16:05
I am under the impression that this is a beta 2 issue and not an issue with `SideMenu` itself.
Hopefully beta 3 resolves this, but definitely makes it difficult to test certain **large** aspects of an application, thanks Apple.

**Comment by kamerc** [comment] 2020-10-05 17:46
My app is functioning fine until I select the button to open the side menu. Once I do, the entire app appears disabled/frozen. Unlike @OIO-WPK, the menu does not open for me once. I tested the SideMenu Example app and am seeing the same behavior that I saw in my own app.

**Comment by DanielFontes** [comment] 2020-10-05 20:30
Duplicate of #652

**Comment by jakemor** [comment] 2020-10-10 12:57
Same Issue - there is a memory leak

**Comment by PasqualePuzio** [comment] 2020-10-10 13:59
Same issue here. This may be an issue caused by a buggy iOS beta, however in order to avoid urgent issues the day of the public release, i would definitely suggest to fix it as soon as possible.

**Comment by jonkykong** [comment] 2020-10-10 17:56
I’d like to empower anyone here using the beta to investigate a fix for the community.

I will not be updating until the stable build drops.

**Comment by DanielFontes** [comment] 2020-10-12 12:58
I got something. If I comment-out transitionController?.layout() in SideMenuNavigationController the menu shows up.

`
    open override func viewWillLayoutSubviews() {
        super.viewWillLayoutSubviews()
        //transitionController?.layout()
    }
`

**Comment by PasqualePuzio** [comment] 2020-10-12 13:49
This is a great finding @DanielFontes 

Where would you move presentingVC.view.untransform ?

> I got something. If I comment-out `transitionController?.layout()` in SideMenuNavigationController the menu shows up.
> 
> ```
>     open override func viewWillLayoutSubviews() {
>         super.viewWillLayoutSubviews()
>         //transitionController?.layout()
>     }
> ```
> 
> **UPDATE**: `presentingVC.view.untransform {}` in `containerViewWillLayoutSubviews()` in SideMenuPresentaionController causes SideMenuNavigationController to re-layout which will result in an endless loop.

**Comment by DanielFontes** [comment] 2020-10-12 14:05
> Where would you move presentingVC.view.untransform ?

At the moment I just want to figure out why it's causing an endless loop only on iOS 14.2 beta 2 and not before.

**Comment by DanielFontes** [comment] 2020-10-12 17:47
It's definitely an iOS bug. After updating the frame of the menu, all constraints regarding the width should be updated as well, but for some reason the width-constraint of the navigationbar isn't updated.

```
<NSLayoutConstraint:0x600001ae9450 'UIView-Encapsulated-Layout-Width' Example.SideMenuTableView.width == **240**   (active, names: Example.SideMenuTableView:0x7fe92c028350 )>
<NSAutoresizingMaskLayoutConstraint:0x600001ae9180 h=--& v=--& _UINavigationBarContentView:0x7fe92c028770.width == **375**   (active)>
```

On iOS < 14.2 beta 2:
```
<NSLayoutConstraint:0x60000003f7a0 'UIView-Encapsulated-Layout-Width' Example.SideMenuTableView.width == **240**   (active, names: Example.SideMenuTableView:0x7f998b416e40 )>
<NSAutoresizingMaskLayoutConstraint:0x60000001e6c0 h=--& v=--& _UINavigationBarContentView:0x7f998b40dc10.width == **240**   (active)>
```

I think that's the reason for the `viewWillLayoutSubviews()` loop

**Comment by sandymarieli** [comment] 2020-10-13 00:08
Hi, I just resolved this issue, well, maybe only a part, what I made was:
In the class SideMenuPresentationController
- I comment-out the line that set the width of the Menu's view, line 230
   **//rect.size.width = config.menuWidth**
- Set the size of the presentedViewController as follow, same class, line 85, method **containerViewWillLayoutSubviews**
       **presentedViewController.view.frame.size = CGSize(width: config.menuWidth, height: 
       presentedViewController.view.frame.height)**

Is still crashing me when presente a VC, so, I'm going to searching to a fix.
PD: Sorry for my bad english.

**Comment by DanielFontes** [comment] 2020-10-13 13:23
I think it's more of a autolayout bug because after setting the width of the the menu it's always resetting to the device width and this always triggers `viewWillLayoutSubviews()`

**Comment by sandymarieli** [comment] 2020-10-13 14:21
Yeah, there's a infinite loop in `viewWillLayoutSubviews()`. It's a temporary way to avoid the crash, at least to my needs, I hope the next beta resolve this issue.

**Comment by DanielFontes** [comment] 2020-10-13 15:52
This is my temporary fix: f40c09ec49321f76f1fc4cb87a0fb178cacb410a

**Comment by Hackmodford** [comment] 2020-10-13 16:02
Do we actually know if there will be another beta before release?
Has anyone filed a radar for this issue?

**Comment by DanielFontes** [comment] 2020-10-14 00:26
Can confirm that it has been fixed with 14.2 beta **3**

**Comment by PasqualePuzio** [comment] 2020-10-14 09:13
> Can confirm that it has been fixed with 14.2 beta **3**

That's great news

**Comment by quensen** [comment] 2020-10-15 06:11
Confirmed. Fixed with public beta 3.

**Comment by jonkykong** [comment] 2020-10-15 08:50
Thank you all for you continued updates and support. I am marking this issue as resolved.

**Closed by jonkykong** 2020-10-15 08:50 UTC
Labels: Bug - Help Wanted!
