### ISSUE TITLE
Updating menu width when it is displayed

### ISSUE THREAD

**Issue by AndriyGo** [jonkykong/SideMenu#366] opened 2018-06-03 15:51 UTC
## New Issue Checklist

I have read the [guidelines for contributing](https://github.com/jonkykong/SideMenu/blob/master/.github/CONTRIBUTING.md) and I understand:
- [x] My issue is happening in the **latest version** of SideMenu.
- [x] My issue was **not** solved in the [README](https://github.com/jonkykong/SideMenu/blob/master/README.md).
- [x] My issue can **not** be answered on [stackoverflow.com](stackoverflow.com).
- [ ] My issue is **not** a request for new functionality that I am unwilling to build and contribute with a pull request.
- [x] My issue **is** reproducible in the [demo project](https://github.com/jonkykong/SideMenu/tree/master/Example).

## Issue Description
I want to change the width of the menu when it is displayed. The reason is simple – at the top of my left menu there is a search bar and when the user clicks on it I want the search controller to occupy all screen.

I tried to do the following hack when search controller is presented:

```
UIView.animate(withDuration: 0.35, animations: {
            SideMenuManager.default.menuLeftNavigationController?.view.frame.size.width = UIScreen.main.bounds.size.width
            let delegate = UIApplication.shared.delegate as! AppDelegate
            delegate.window?.rootViewController?.view.frame.origin.x = UIScreen.main.bounds.size.width
        })
```

It works, but for some unknown reason when Cancel button is pressed, the menu gets closed. So, it looks like I need to submit a PR to support menu width change.

So far, I am struggling to understand how to do this. I will try to come up with this PR myself, but if you could give me some advice it would be great. It is especially challenging since I do not understand what causes such a weird behaviour with search controller in the first place...

## Update 1
Menu gets closed because `tapView` bounds are not changing. Hence, when I click on the Cancel button I trigger `handleHideMenuTap` function.

**Comment by jonkykong** [comment] 2018-06-04 03:50
Hi @AndriyGo, thanks for opening up an issue.

As this is not a bug but more of a change request, and the first request of its kind for this functionality, I would prioritize it as *low* for the community. Therefor I am not going to undertake this fix myself. As you stated you are welcome to submit a PR yourself. I'm closing this issue for now, but feel free to keep updating/commenting and I will respond as necessary.

You might try `menuPresentingViewControllerUserInteractionEnabled` as that will prevent the tapView from being created. You would still need to turn off user interaction on your presenting view controller yourself to prevent accidental touches.

**Closed by jonkykong** 2018-06-04 03:50 UTC

**Comment by rintoandrews90** [comment] 2019-10-25 16:11
is there any update regarding this feature. This is really cool feature to have.

UIView.animate(withDuration: 0.35, animations: {
            SideMenuManager.default.menuLeftNavigationController?.view.frame.size.width = UIScreen.main.bounds.size.width
            let delegate = UIApplication.shared.delegate as! AppDelegate
            delegate.window?.rootViewController?.view.frame.origin.x = UIScreen.main.bounds.size.width
        })

does this work

**Comment by jonkykong** [comment] 2019-10-25 17:46
@rintoandrews90 you're welcome to open up a PR with a solution to this feature. Unfortunately I don't have time to build it.
