### ISSUE TITLE
Pan Gestures calling dismissViewControllerAnimated even if it's not going to be dismissed

### ISSUE THREAD

**Issue by danfsd** [jonkykong/SideMenu#84] opened 2016-10-10 20:45 UTC
The `SideMenuTransition.handleHideMenuPan(_:)` is calling `viewControllerForPresentedMenu?.dismissViewControllerAnimated` even though the menu won't be dismissed at all.

For instance, my menu is setup up on the **RIGHT SIDE**. If I make a pan/swipe gesture from the **right** to the **left**, the menu won't be dismissed but the `viewWillDisappear` method of the `viewControllerForPresentedMenu` is called.

This may generate some misleading and confusion for the developers when using your code with other libraries, such as my case: I'm using a blur library to blur everything behind the menu. When the menu is closed, the blur hides. So I was using the `viewControllerForPresentedMenu.viewWillDisappear` to make this arrangements, but since it's being called even when the menu won't be dismissed I wasn't able to make this flow to work properly.

Any workarounds or delegate calls that are only called when the menu will actually be hidden?

**Comment by danfsd** [comment] 2016-10-10 21:10
I was able to solve the issue by checking the orientation of the `UIPanGestureRecognizer` (by it's velocity) and comparing to the **SideMenuTransition.presentDirection** like so:

```swift
case .Began:
    singleton.interactive = true
    let velocity = pan.velocityInView(pan.view!)
    if (direction == 1 && velocity.x > 0) || (direction == -1 && velocity.x < 0) {
          viewControllerForPresentedMenu?.dismissViewControllerAnimated(true, completion: nil)
    }
```

What are your thoughts on this? Is this behavior expected by you or should I make a **Pull Request**?

**Comment by jonkykong** [comment] 2016-10-10 21:47
@danfsd am I correct in understanding that if the user begins swiping in any direction that does **not** result in the menu visually beginning to disappear that viewWillDisappear is still called? If so, this is by design. A user could start moving their finger in the wrong direction, but then back in the correct direction. Their movement is essentially unpredictable so the check you're adding doesn't properly account for what you're trying to catch.

Instead, I would suggest using `viewDidDisappear`, or by looking into the appearance events of your `UISideMenuNavigationController` to drive the desired results. If that doesn't work, a more detailed solution would involve a subclass of `SideMenuTransition` which is currently marked as `internal`. It would instead need to be made `open` so that you could subclass it for the desired effects.

If you are interested in submitting a PR to make `SideMenuTransition` and the necessary properties `open`, I'd be willing to entertain merging it.

**Comment by danfsd** [comment] 2016-10-10 22:23
I think that by using `viewDidDisappear` should solve the problem. Silly me, forgot about the basics of the View-controller lifecycle.
Thanks for the quick response, I'll get back tomorrow with an answer.

**Closed** 2016-10-11 01:13 UTC
