### ISSUE TITLE
Strange behavior after fast swipe

### ISSUE THREAD

**Issue by Nominalista** [jonkykong/SideMenu#297] opened 2017-11-28 18:58 UTC
## New Issue Checklist
I have read the [guidelines for contributing](https://github.com/jonkykong/SideMenu/blob/master/.github/CONTRIBUTING.md) and I understand:
- [x] My issue is happening in the **latest version** of SideMenu.
- [x] My issue was **not** solved in the [README](https://github.com/jonkykong/SideMenu/blob/master/README.md).
- [ ] My issue can **not** be answered on [stackoverflow.com](stackoverflow.com).
- [x] My issue is **not** a request for new functionality that I am unwilling to build and contribute with a pull request.
- [x] My issue **is** reproducible in the [demo project](https://github.com/jonkykong/SideMenu/tree/master/Example).

## Issue Description

After fast swipe (like here: https://media.giphy.com/media/l2RnuP9o4ykUhmINi/200w.gif) the animation is very slow. Is it related to mentioned issue in README, because it's on iOS 11?

**Comment by jonkykong** [comment] 2017-11-28 19:41
Near as I can tell this is some strange underlying behavior of the `UIScreenEdgePanGestureRecognizer` on a fast swipe OR the transition being ended quickly.

I'm not inclined to spend time to produce a fix for this given the following:
- It's not easily reproduced.
- It still works.
- This is the first report of this problem.

@Nominalista You're welcome to investigate further and produce a fix as a PR to this library.

**Closed by jonkykong** 2017-11-28 19:41 UTC

**Comment by NikKovIos** [comment] 2018-05-07 07:35
Same problem. When menu didn't opened the first swipe looks like in the video. After menu opened one time, the other swipes work like expected.

**Comment by jseidman95** [comment] 2018-08-01 04:00
Im having the same exact issue as @NikKovIos. Right after start up the menu opened with a slow animation and then from then and onwards it worked normally

**Comment by NikKovIos** [comment] 2018-09-25 21:36
For me fixed in `SideMenu (5.0.1)`

**Comment by disquad** [comment] 2018-10-12 21:47
Have same problem, first open like in slow motion
