### ISSUE TITLE
ViewControllers push same instance issue

### ISSUE THREAD

**Issue by geekkon** [jonkykong/SideMenu#242] opened 2017-08-16 16:30 UTC
## New Issue Checklist

I have read the [guidelines for contributing](https://github.com/jonkykong/SideMenu/blob/master/.github/CONTRIBUTING.md) and I understand:
- [x] My issue is happening in the **latest version** of SideMenu.
- [x] My issue was **not** solved in the [README](https://github.com/jonkykong/SideMenu/blob/master/README.md).
- [x] My issue can **not** be answered on [stackoverflow.com](stackoverflow.com).
- [x] My issue is **not** a request for new functionality that I am unwilling to build and contribute with a pull request.
- [ ] My issue **is** reproducible in the [demo project](https://github.com/jonkykong/SideMenu/tree/master/Example).

## Issue Description

Hello. Thanks for great SideMenu implementation!
I instantiate SideMenu from AppDelegate and MenuViewController (UIViewController subclass) as a root. In MenuViewController I call push... func and pass ViewController_1() to it. But when I switch another viewController, first one does not deinit, and when I switch back it creates another instance of ViewController_1(). Sow I suppose it is a memory leak isn't it?
And I decide to create and hold viewControllers instances in MenuViewController and push same instance when need, and I can't do this because  of "Pushing the same view controller instance more than once is not supported". How can I use one Instance of ViewController per menu type? Thanks!

**Comment by jonkykong** [comment] 2017-08-16 16:42
This is by design.

As a singleton, it retains a reference to the menu you assign to the menu so you can easily call the menu programmatically from any screen.

To enable storyboard simplicity, there is no way to tell interface builder to use the existing instance, so instead if it recreates a VC for the menu and that takes over for any existing menu previously held.

From a design standpoint, you should restore your menu back to the desired state every time it appears, not every time it is initialized.

**Closed by jonkykong** 2017-08-16 16:42 UTC

**Comment by geekkon** [comment] 2017-08-16 16:51
Ok, retain reference is not bad, but not to release it is not good for memory, because you not reuse holded viewController and forces to create new. Is it possible to push the same instance of VC several times?

**Comment by geekkon** [comment] 2017-08-16 16:54
Oh, you sad it retains Menu - it's OK. I'm telling about menu elemets (as ViewControllers)

**Comment by jonkykong** [comment] 2017-08-16 16:56
I'm not familiar with your design, but of course it's possible. Either use a new instance or release the old one before pushing it again. There's plenty on StackOverflow about that.

**Comment by geekkon** [comment] 2017-08-16 17:02
Is it an explicit way how to release old one instance?

**Comment by jonkykong** [comment] 2017-08-16 17:05
Set the menu to nil when you're done with it.

**Comment by jonkykong** [comment] 2017-08-16 17:05
Or reset it back to a new instance.

**Comment by Wolfaks** [comment] 2017-08-25 07:50
Please, tell me how to do this?

> Set the menu to nil when you're done with it.
> Or reset it back to a new instance.

**Comment by Wolfaks** [comment] 2017-08-28 07:52
@jonkykong Please, tell me how to do this?

> Set the menu to nil when you're done with it.
> Or reset it back to a new instance.

**Comment by wolfej94** [comment] 2020-02-28 11:45
@jonkykong sorry to revive an old thread but how would you go about doing this if you setup sidemenu with a storyboard?
