### ISSUE TITLE
Screen freeze issue in iOS 10

### ISSUE THREAD

**Issue by SanjithKanagavel** [jonkykong/SideMenu#130] opened 2017-01-12 07:00 UTC
## New Issue Checklist

I have read the [guidelines for contributing](https://github.com/jonkykong/SideMenu/blob/master/.github/CONTRIBUTING.md) and I understand:
- [x] My issue was **not** solved in the [README](https://github.com/jonkykong/SideMenu/blob/master/README.md).
- [x] My issue can **not** be answered on [stackoverflow.com](stackoverflow.com).
- [x] My issue is **not** a request for new functionality that I am unwilling to build and contribute with a pull request.
- [x] My issue **is** reproducible in the [demo project](https://github.com/jonkykong/SideMenu/tree/master/Example).

## Issue Description

I could add the left and right menu. But I can't swipe back to main controller. The UI gets freezes up. when i try to swipe back to main screen. iOS 10.2 + xcode 8.2.1. Please check.  I am tried using code. When i inspect in view hierarchy i could see the expected view after swipe. But in device its getting freezed.

**Comment by SanjithKanagavel** [comment] 2017-01-12 07:32
@jonkykong Reproducing in the example project itself. Please check. Swipe freeze the UI.

**Comment by jonkykong** [comment] 2017-01-12 09:35
You could not have tried the demo project since you are not using storyboard.

There are a lot of reasons why this may not be working for you as you have provided very little information (including how you set up the menus, when it freezes, etc.).

You must create a new project that clearly reproduces the problem (removing any of your unrelated code) and share a link to that project.

**Comment by SanjithKanagavel** [comment] 2017-01-12 09:41
Steps i did:  
- Cloned the git repo in master branch
- Changed the signing credentials and i dint change any line of code.
- Ran the project in iOS 8.3 iPad. 
- Swiped left menu bar. It worked.
- Did the right swipe inside the left menu bar. And now the screen is fixed.
- But when i inspect the UI Hierarchy. It showed the main view-controller. 

You have added few codes in 2.1.4 from 2.1.0 in pan gesture. I think its making the issue. 

PS : Try this and lemme know still you cant reproduce the issue.

**Comment by jonkykong** [comment] 2017-01-12 22:21
@SanjithKanagavel this should be fixed in 2.1.5.

**Closed by jonkykong** 2017-01-12 22:21 UTC
Labels: Bug
