### ISSUE TITLE
Application crashes after touch home button

### ISSUE THREAD

**Issue by misha83** [jonkykong/SideMenu#2] opened 2016-01-21 13:24 UTC
Application crashes for me after touching home button.In SideMenuTransition.hideMenuStart() SideMenuTransition.viewControllerForPresentedMenu! controller is nil. 
My init looks like:
```
 let leftViewController:UISideMenuNavigationController = UIStoryboard(name: "Main", bundle: nil).instantiateViewControllerWithIdentifier("UISideMenuNavigationController") as! UISideMenuNavigationController
         SideMenuManager.menuLeftNavigationController = leftViewController
        SideMenuManager.menuAddScreenEdgePanGesturesToPresent(toView: self.view)
        SideMenuManager.menuPresentMode = .MenuSlideIn
        SideMenuManager.menuAnimationBackgroundColor = UIColor.clearColor()
```

**Comment by jonkykong** [comment] 2016-01-21 22:00
Hi @misha83, I'm not able to reproduce this problem using the latest build of the library with my iPhone 6S running 9.2. Can you re-run `pod install` on your project and give it another try? If it still happens, please give me more details as to how I can recreate this issue.

Also, you don't need to explicitly set `SideMenuManager.menuAnimationBackgroundColor = UIColor.clearColor()` as it starts out this way.

**Comment by jonkykong** [comment] 2016-01-22 05:15
Closing until more feedback is provided.

**Comment by barankaansert** [comment] 2016-04-25 18:35
i also had same problem with this line comes to nil. Please give me a solution about that?

**Comment by jonkykong** [comment] 2016-04-25 18:38
Hi @barankaansert. I still cannot reproduce this issue. I'd need more feedback about the problem similar to my request to @misha83 above.

**Comment by leizard** [comment] 2016-05-09 08:52
Hi @jonkykong, I created a cell and create a segue from this cell back to the frontView (home view). When I run and click that cell, the above issue happens.

**Comment by jonkykong** [comment] 2016-05-09 09:00
@leizard what exception are you getting? Is this an unwind segue?

**Comment by leizard** [comment] 2016-05-09 09:07
I use one side menu for multiple view. So when I'm at a subview, I want to open side menu and click 'Home' item to go back to Home. The issue happen when I'm currently at home view and click to the Home item in side menu. And yes, it is an unwind segue

**Comment by jonkykong** [comment] 2016-05-09 09:09
@leizard what exception are you getting?

**Comment by leizard** [comment] 2016-05-09 09:25
I'm sorry for not reading your reply carefully. The exception is the same as the first post. In internal class func hideMenuStart() , SideMenuTransition.viewControllerForPresentedMenu! controller is nil. and it crashes.
I just comment out 
`
SideMenuManager.menuLeftNavigationController = storyboard!.instantiateViewControllerWithIdentifier("LeftMenuNavigationController") as? UISideMenuNavigationController
`
in my menu init and it doesn't crash anymore

**Comment by jonkykong** [comment] 2016-05-09 09:36
Why does commenting that out in your init solve the problem? It sounds like you're removing the menu entirely because of that. Is the init called again when you return to your home screen?

**Comment by jonkykong** [comment] 2016-05-09 17:57
@leizard I have a theory -- can you verify? My guess is that unwind segues cause the view to be reinitialized, whereas popping/pushing on the stack don't do that. If you're setting up SideMenu in your home view, then any time you unwind to it from the menu, you're replacing the side menu while it's presented, causing this crash.

If instead you initialized SideMenu from your app delegate, or put a simple check in your init that it should only set `menuLeftNavigationController` if it was nil, that should resolve the crash.

Let me know what you find.

**Comment by fajaradiwa** [comment] 2016-05-10 04:29
@leizard i got same issues before ..... you can try change value for SideMenuManager.menuAddScreenEdgePanGesturesToPresent(toView: self.view) 
to 
SideMenuManager.menuAddScreenEdgePanGesturesToPresent(toView: leftViewController.view)

hopely it can help ...

**Comment by jonkykong** [comment] 2016-05-10 04:59
Any chance you have a project you can share with me to investigate?

**Comment by leizard** [comment] 2016-05-10 09:36
I'm diving other issues and can't test your suggestion right now. I will response asap when I can.
Thank you very much for your time and quick replies @jonkykong @fajaradiwa

**Comment by leizard** [comment] 2016-05-13 03:58
Hi @jonkykong, I think you are right. I put a check like this

`
        if (SideMenuManager.menuLeftNavigationController == nil) {
            SideMenuManager.menuLeftNavigationController = storyboard!.instantiateViewControllerWithIdentifier("LeftMenuNavigationController") as? UISideMenuNavigationController
        }
`
in my frontview controller 
And everything is fine.
So I'm closing this issue.
Thank you very much for your support 👍

**Comment by leizard** [comment] 2016-05-13 04:06
But I think it is better to detect if it is prepare to segue to the same frontview in prepareForSegue method, so if it is, I just need to close the side menu

**Comment by jonkykong** [comment] 2016-05-13 05:26
@leizard I'm thinking I will fix this by preventing the left or right side menus from being changed while they are actively presented. If this happens, I'll display a warning in the console and ignore the change, preventing the exception. Thoughts?

**Comment by leizard** [comment] 2016-05-14 04:43
Hi @jonkykong, sorry for late response. As I understand, each view has to register their side menu. So I want 1 side menu on multiple view, I have to register this side menu multiple times. In other words, I will lose my side menu when I go to another view. Please correct me if I'm wrong.
So, when I put a item segue to the presenting front view and click it, the front view will reload again, which it doesn't need to because it is the same view. I think your fix could solve this but I don't it fits in a scenario when we want a side menu on multiple view.

**Comment by jonkykong** [comment] 2016-05-14 04:45
@leizard that is incorrect. The design of SideMenu is such that you can set it up once and reuse it on multiple screens. At most you have to wire up buttons to present the left/right menus or gestures to reveal them, but you don't need to set the left/right menu more than once (unless you want to change them on purpose).

**Comment by jonkykong** [comment] 2016-05-14 08:52
@leizard @fajaradiwa @misha83 @barankaansert I checked in a fix that prevents side menus from being changed while the menu is actively presented, which would cause crashes.

**Closed by jonkykong** 2016-05-14 08:52 UTC

**Comment by leizard** [comment] 2016-05-15 03:25
Thank you @jonkykong, I think it would do it.
