### ISSUE TITLE
App creash.

### ISSUE THREAD

**Issue by kunj369** [jonkykong/SideMenu#99] opened 2016-11-17 06:25 UTC
I am using swift 2.3 and app creash on below line
This is log from fabric
SideMenuTransition.swift line 160
specialized static SideMenuTransition.hideMenuStart() -> ()

SideMenuTransition.swift line 356
SideMenuTransition.(animateTransition(UIViewControllerContextTransitioning) -> ()).(closure #1)
App is crash on ios 10 device.
Please help me with this.

**Comment by jonkykong** [comment] 2016-11-17 07:59
@kunj369 you haven't provided any useful information for me to help you.

For starters, you should provide more specific steps I can perform to experience this crash. Second, you should be able to follow those steps to reproduce the crash using the demo project.

Its possible this is a crash caused elsewhere in your code that seems like it's caused by SideMenu.

I'm closing this until you provide more useful information.

**Closed by jonkykong** 2016-11-17 07:59 UTC
